### ISSUE TITLE
PDB Length requirement

### ISSUE THREAD

**Issue by jadolfbr** [BioinfoMachineLearning/ATOMRefine#1]
Hello,

Looking forward to trying this code out, but why the requirement of the PDB length when you are reading the PDB for refinement?  What is the goal/use of this?  Also - does your model work with multiple chains?

**Comment by ZhiYeG** [comment]
Hi,
Due to the most extensive GPU memory that we can obtain, so we can't handle those too-long targets. And this tool didn't test on multiple chain targets, I can't think it can work on targets like that.
