### ISSUE TITLE
ATOMRefine fails immediately when using pyRosetta generated PDBs

### ISSUE THREAD

**Issue by bernym12** [BioinfoMachineLearning/ATOMRefine#3]
I was attempting to generate refinements for a few pyRosetta generated PDBs and it immediately failed; however, the example files provided seem to work as well as AlphaFold2 generated PDBs. I've attached the PDB used as well as the error reported. 

./refine.sh model1.pdb T1104 117 output/
>Traceback (most recent call last):                                                                                                                                                             File "/home/grads/bernardm/ATOMRefine/predict.py", line 231, in <module>                                                                                                                       bond = bond.reshape(1,L,L,1)                                                                                                                                                             RuntimeError: shape '[1, 967, 967, 1]' is invalid for input of size 2531281

[model1.pdb.txt](https://github.com/BioinfoMachineLearning/ATOMRefine/files/11667053/model1.pdb.txt)

**Comment by ZhiYeG** [comment]
Hi, I have looked into this problem. However, it seems it is the error in the pdb file, more specifically, the sidechain. Have you ever tried out another pdb file? Or does the example pdb file work for your side?

**Comment by ZhiYeG** [comment]
> 

I did furthermore experiment. Try to use [post_amber.py](https://github.com/BioinfoMachineLearning/ATOMRefine/blob/main/post_amber.py) to do the relaxation of your pdb file. After this post-process, the out pdb file worked fine for ATOMRefine.

**Comment by bernym12** [comment]
Thank you for your help! Just to answer your other questions, the method works fine with other PDBs such as those generated by AlphaFold2. Also my original PDBs did work with other refinement methods such as GNNRefine.
