### ISSUE TITLE
RuntimeError: shape '[1, 824, 824, 1]' is invalid for input of size 2715904

### ISSUE THREAD

**Issue by Le-Phung-Hien** [BioinfoMachineLearning/ATOMRefine#4]
Hi team,

I am trying to use ATOMRefine to refine a structure of a **dimeric** protein in pdb file. I keep getting this error: 
`sh refine.sh example/qacC.pdb qacC 214 output
Using backend: pytorch
Global seed set to 2000542198
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/mnt/d/ATOMRefine/amber/stereo_chemical_props.txt
AmberRelaxation has been done on /mnt/d/ATOMRefine/output/qacC.pdb!
[['/mnt/d/ATOMRefine/output/qacC.pdb', '/mnt/d/ATOMRefine/output/qacC.pdb']]
Start prediction ...Predict each model may take 4 or 5 mins...In total, 5 models will be generated....
qacC....model1
Traceback (most recent call last):
  File "/mnt/d/ATOMRefine/predict.py", line 236, in <module>
    bond = bond.reshape(1,L,L,1)
RuntimeError: shape '[1, 824, 824, 1]' is invalid for input of size 2715904`

I have try this file which also include a ligand (a Modeller generated structure and the main one I want to refine):
[qacC.pdb.txt](https://github.com/BioinfoMachineLearning/ATOMRefine/files/11934837/qacC.pdb.txt)

And this Alphafold generated file which do not contain the ligand:
[qacC_alphafold.pdb.txt](https://github.com/BioinfoMachineLearning/ATOMRefine/files/11934852/qacC_alphafold.pdb.txt)

Both generate the same error.

I will appreciate any input!

Thanks!

**Comment by ZhiYeG** [comment]
Both two pdb file you provide are protein complex structure. I don't think ATOMRefine can work on the complex structure. If you want to try it on the complex structure, you may need to remove the TER between chains and rename to one same chain name. However, ATOMRefine didn't do any test on complex structure, so the results may not reliable.

**Comment by Le-Phung-Hien** [comment]
Thanks for the clarification!
